language: python
python:
- '2.7'
git:
  depth: 1
sudo: false
env:
  global:
  - VASP_PSP_DIR=`pwd`
  - USERNAME=mashton
  - secure: JkVMFGuY+zwD69mON4HtwSEWKEXAPnKekQUzcIM3jB+zje7qVHOfu0gLwsSpHKgamUwtcxxAxT1oYCuZkRZ31PN6AWBX/J+NIT/+Bxj/lQF7L9SHUKI1CRk5PK+Xre9t1lcu1QibM6aV1C1TV0ccWNn00gYktHpmSvL9AO1Hz/iGslmFPQrYcotmjbS/T489J+rTYJk71asMMC8MVV7AEdLwBZsu+dCTyOfczSCswmFd2oQiiYkFVa7CrD1mKUYcjZ1Mxmq4VIfRm6tIKTKAKliajZwFav5eJ5vwmPqczOkiAE/0/aK59CC6RT9S97SpdvWC3rjOTY5LxkvydKu8WUYla6ZKHvaZxfDgsK5g+Od+skwXgk9u1WUNCUbDdPkBGdUX0QhhFvMba6fhqnDMW1AbbwF4qZkTOGn2T4X+Xp1VNa/4Rkk0otYf0rTiJ8Q+kbIw0VW6RN70oQXl8IFdBhsK551Wc8IaID+rh+cB52XGk8891KpdKU6ADnV+4YV74+eE6EEVgDBXBmQQIZHbTkMdxUkAd0JdepwDNdrWziXWXQM2w+i8x4wxPofnOU3b2vR82WnAxBPVsE66d8sXRuCZbPj3nDrHIEocTN4EaCfIFThU3A8rSOxo1sQRCeJ05xu5VUpzwZ9TkCxpF0g7tTSeEF4UlAy0tkINc6IW7ws=
addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - python-scipy
    - python-pip
install:
- travis_wait pip install -q -r requirements.txt
before_script:
- python setup.py develop
script:
- nosetests twod_materials
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - mashton@ufl.edu
    on_success: change
    on_failure: always
