username: null  # your UF HPC username
mp_api: null  # your Materials Project API key
normal_binary: null # /path/to/std/vasp/executable
twod_binary: null  # /path/to/2D/vasp/executable
vdw_kernel: null  # /path/to/vdw_kernel.bindat  (leave as null if the kernel is hard-coded into VASP)
potentials: null  # /path/to/POTCAR/files
queue_system: slurm  # Change to pbs if on a PBS system
queue_template: config_files/ #path/to/queue/template containing account info, processor config 'submit_script'
